name: Deploy Angular App to S3 with Terraform

on:
  push:
    branches:
      - ftr-aws-cloudfront-deploy

jobs:
  deploy:
    name: Terraform + Upload App
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node (for Angular build)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular deps
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Upload app to S3
        run: |
          aws s3 sync dist/front_spotistats s3://${{ secrets.S3_BUCKET_NAME }} --delete
